### ISSUE TITLE
gpu_replay.cpp: missing <climits> include breaks build on GCC 16 (INT_MAX not declared)

### ISSUE THREAD

**Issue by mattias800** [mattias800/prosper#1008]
## Summary

`tools/gpu_replay/gpu_replay.cpp` uses `INT_MAX` (lines ~1200 and ~1206, in the argument parsing added
for capped numeric options) without including `<climits>`. On toolchains where the constant leaks in
transitively (older GCC/libstdc++, MSVC/MinGW) this compiles; on **GCC 16.1 / Fedora 44** the transitive
include is gone and the build fails:

```
tools/gpu_replay/gpu_replay.cpp:1200:54: error: 'INT_MAX' was not declared in this scope
tools/gpu_replay/gpu_replay.cpp:1206:54: error: 'INT_MAX' was not declared in this scope
```

This breaks the default `cmake --build` of current `master` (698ef53) on newer-GCC hosts, and with it
the `gpu_capture_render_replay` ctest (its `gpu_replay` dependency never links, test reports Not Run).

## Fix

Add `#include <climits>` to `gpu_replay.cpp`'s standard includes. One line; verified to restore the full
633-target build on GCC 16.1.

Environment: Fedora 44 distrobox (GCC 16.1.1), native Linux.
