### PR TITLE
hle(fiber): implement sceFiberRename instead of leaving it to the return-0 default

### PR DESCRIPTION
**Pull request by mattias800**
An unregistered NID falls to the dispatcher's `return 0`, which answers `SCE_OK` while doing nothing — so a guest that renames a fiber is told it succeeded and then reads back the old name. This implements it for real.

prosper already carries the only state involved: `GuestFiber::name` is the 32-byte field this file fills at initialize and prints in its own `[fiber] init` diagnostic. Nothing has to be guessed.

> **Round 1 was rejected, and the central finding falsified my justification.** The implementation needed no change; every blocking finding was a false claim shipping beside correct code, one of them in a source comment. They are recorded rather than quietly fixed.

## Why it is here — corrected

I claimed the title "exercises" this NID because it appears in the eboot's import table. **Importing is not calling.** `tools/re/nid_gate_scan.py` — a tool that exists for exactly this question, its docstring opening *"Importing a NID is not the same as depending on what it returns"* — finds **zero call sites** for `JzyT91ucGDc` in both `eboot.bin` and `tllr-boot.bin`.

The zero is controlled, not silent: the same tool on the same binaries reports call sites for `hVYD7Ou2pCQ`, `a0LLrZWac0M` and `asjUJJ+aa8s`. **The title links this function and never calls it.**

So the honest justification is narrower, and it is the one in the source now: the implementation is complete, needs no reverse engineering, costs one bounded copy, and removes a silent-wrong answer from a linked entry point. That reasoning does not extend to guessing at a struct layout — and deliberately does not.

## Corrected counts

The first version said "5 of 10 exports". libSceFiber has **15**; prosper registered **6**, now **7**; **8** remain unregistered.

The error was a grep pattern — `__ptr_sceFiber[A-Za-z]+` — that excluded the **five** leading-underscore entry points: `_sceFiberAttachContextAndRun`, `_sceFiberAttachContextAndSwitch`, `_sceFiberGetThreadFramePointerAddress`, `_sceFiberInitializeImpl` and `_sceFiberInitializeWithInternalOptionImpl`. 15 − 5 = 10 is what produced the bogus count.

The fifth matters twice over: `_sceFiberInitializeImpl` is one prosper **already registers**, so the pattern under-counted both the library *and* prosper's own coverage. The others are the alternate initialization paths that would decide whether an error return could regress a different title, so the wrong framing also hid the set governing regression risk. A pattern one character too narrow, failing silently toward "nothing there".

## Still not implemented: `sceFiberOptParamInitialize`

Its contract is to initialise a struct whose **size prosper does not know**. Writing too many bytes corrupts the guest's stack; writing none is the stub. That decision stands.

**But the first version's reason for it was wrong.** I said the call site was unreachable, having tried `xref.py` — which is address-based. `nid_gate_scan.py` locates it: image-relative **`0x1f08`**, gated `test eax,eax`. The size is obtainable by disassembling that call site. It is **not done, rather than impossible** — and `fiber_initialize` ignores optParam entirely (`hle_fiber.cpp:305-307`), so nothing depends on it today.

## Tests — and the first transcript was mislabelled

Round 1 quoted a two-arm failure as *"a registered no-op, exactly what the `return 0` default does"*. That evidence came from a **different mutation** (validation kept, only the copy removed). The true dispatcher default reddens **four** arms, because the null-fiber and null-name arms also stop refusing:

```
[FAIL] sceFiberRename actually renames the fiber ...
[FAIL] ...and an over-long name is truncated INTO the 32-byte field ...
[FAIL] a null fiber is refused
[FAIL] a null name is refused
== FAIL: 4 ==
```

Unregistering the NID instead reddens exactly **one** arm — the registration arm — because the behaviour arms sit behind `if (rename_fn)`. The pair distinguishes **missing** from **present but fake**.

The name field's *offset* is guarded by a control (initialize stored `"test"` there) and its *size* by the truncation arm — separate arms, both loud.

## Confidence

**HIGH** on the copy (the field is prosper's own) and on the NID mapping (`JzyT91ucGDc` is unique across the 3.20 firmware set).

**LOW**, marked in the source, on three semantics that are inferred rather than established, none of which any corpus title can currently exercise: whether a **running** fiber may be renamed (`fiber_finalize` refuses `kStateRun`; this does not), whether an over-long name truncates-and-succeeds or returns a range error, and the `kErrInvalid`/`kErrNull` split.

## Verification

```
cmake --build prosper/build-linux -j6      # BUILD_RC=0
ctest --no-tests=error                     # CTEST_RC=0
100% tests passed out of 509
```

Refs #3615

### CODE REVIEW

**Review by mattias800 — COMMENTED** [review]
## REJECTED

Reviewed head **8e01739ab2cc65daca36960ac0b70c4db5585246** (confirmed still the branch tip at review time).

**The implementation needs no change.** I verified it line by line and it is correct, safe, and better tested than the PR body claims. Everything blocking below is a *false claim that ships* — one of them in a source comment, the rest in the PR body. They are cheap to fix and I will approve on a corrected head.

I am rejecting rather than approving-with-nits because the central justification of this change is falsified by measurement, and it is written into `hle_fiber.cpp` as a comment. Per the charter's #2049 account, a shipped code comment is a step in the propagation chain, and a claim with a title id and a NID in it reads as already-checked.

---

## What I verified as correct

* **The NID is right.** `JzyT91ucGDc` -> `sceFiberRename` in libSceFiber, confirmed in the PS5 3.20 firmware reference, and **unique across all 275 libraries** (checked with a discriminator shown to move in both directions: it reports real cross-library duplicates elsewhere, and 0 for a fabricated NID). No risk of registering this body under another function.
* **Registration form.** `(HleFn)` cast is correct here, not a `register_typed` case: `fiber_rename` takes only pointers and returns `uint64_t`, and `dispatch.hpp:104-109` documents the cast and typed forms as equivalent for purely integer/pointer handlers. Matches `fiber_finalize` exactly. `PROSPER_GUEST_ABI` is not wanted (that is for real variadics).
* **Offset 40 is right.** `magic_start` 0, `state` 4, `entry` 8, `initialize_arg` 16, `stack` 24, `stack_size` 32, `name` **40**.
* **Bounds and NUL-termination.** `snprintf` into `sizeof(guest->name)` always terminates. The comment's note that `strncpy` alone would not is correct for this function (`fiber_initialize` gets away with it only because of the preceding `memset`).
* **Thread-safety matches its siblings.** `find_fiber` takes `g_fiber_mutex` and releases it before returning; the subsequent write is to guest memory, exactly as `fiber_finalize` / `fiber_run_impl` / `fiber_switch_impl` do. `find_fiber(nullptr)` only hashes the pointer, so the `!guest || !fiber` order is safe. No new lock is needed.
* **Not the libSceUlt trap.** I specifically checked this. `sceFiberRename` returns a *status*, not a value, so a non-zero return is read as the error code it is — it cannot be consumed as data the way the libSceUlt stub's sentinel was.

---

## Mutation testing — I re-ran both, and the result is not what the body says

| mutation | arms red |
|---|---|
| A. NID unregistered | **1** — the registration arm only |
| B1. body is exactly `return 0` (the true dispatcher default) | **4** |
| B2. validation kept, only the `snprintf` removed | **2** |

Mutation A reproduces as described: the behaviour arms sit behind `if (rename_fn)` and do not even print. The registration arm is a genuine discriminator — `Hle::lookup` returns `nullptr` for an unregistered NID (`dispatch.cpp:167-169`), it does not hand back a default stub.

**But the body says the mutation is "a registered no-op — exactly what the `return 0` default does" and quotes a 2-arm transcript.** A true `return 0` body reddens **four** arms, because the null-fiber and null-name arms also stop refusing. The quoted 2-arm transcript is B2 — a weaker, different mutation. The tests are *stronger* than claimed, so this is in your favour, but the evidence pasted was produced by a mutation other than the one named. Please relabel it (or re-run B1 and paste that).

I also mutated the layout, since the body rests on that control:

* `name` pushed 40 -> 48: **CONTROL reddens** (3 arms red). The offset guard works — it fails loudly rather than letting the arms read wrong bytes and pass.
* `name[32]` -> `name[16]` (offset unchanged): control stays green, **truncation arm reddens**. So the control guards the *offset* and the truncation arm guards the *size*. Different arms, both loud — the pair is adequate. Worth a word in the comment so the next reader does not assume the control covers both.

On brittleness: the hardcoded `40` is defensible given the control. If you want it layout-independent without promoting the struct to a header, scanning the 256-byte block for the init name and asserting it occurs exactly once would locate the field instead of assuming it, and still fail loudly if it vanishes. Optional.

`ctest --no-tests=error` on my build of this head: **509 tests discovered, 100% passed, exit 0**. Matches your count.

---

## Blocking 1 — "exercised rather than speculative" is falsified

This is in the PR body *and* in the code comment at `hle_fiber.cpp:350`.

`prosper/tools/re/nid_gate_scan.py` exists to answer exactly this, and its own docstring opens with the distinction: *"Importing a NID is not the same as depending on what it returns."* Run against this title:

```
<DUMP_ROOT>/PPSA05684-app0/eboot.bin --nid JzyT91ucGDc      ->  (no sites)
<DUMP_ROOT>/PPSA05684-app0/tllr-boot.bin --nid JzyT91ucGDc  ->  (no sites)
```

That zero is **validated, not silent** — same tool, same binaries, four sibling NIDs:

```
hVYD7Ou2pCQ  _sceFiberInitializeImpl       nonzero=1
a0LLrZWac0M  sceFiberRun                   gate-open=1
JeNX5F-NzQU  sceFiberFinalize              gate-open=1
asjUJJ+aa8s  sceFiberOptParamInitialize    nonzero=1
```

So the title emits a JUMP_SLOT for `sceFiberRename` and **never calls it**. The import-table adjacency you cite is real and byte-exact (`asjUJJ+aa8s` at 35029857, `JzyT91ucGDc` at 35029873, nothing between) — but adjacency in `dynstr` is evidence of linking, not of execution, and "present in the import table" was carrying the weight of "exercised" in both the body and the comment.

Caveat I want on the record: the scan reads direct `call rel32` and `call *[rip+d]`. A call through a stored function pointer would be missed, so this is "no statically reachable call site", not "provably never called". It is still the opposite of what the comment asserts.

Two consequences, and the first is good news:

1. **The registration is risk-free for this title.** My main worry going in was that this replaces an always-`SCE_OK` answer with a possible `kErrInvalid` for any fiber absent from `g_fibers`. With zero call sites, nothing in PPSA05684 can observe the new return at all. Separately, the four unregistered init/attach paths that *could* produce such a fiber (`_sceFiberAttachContextAndRun`, `_sceFiberAttachContextAndSwitch`, `_sceFiberInitializeWithInternalOptionImpl`, `_sceFiberGetThreadFramePointerAddress`) are **not imported** by this title, and `fiber_run` / `fiber_switch` / `fiber_finalize` already answer `kErrInvalid` for that same set — so such a fiber is already non-functional and rename is merely consistent. I am satisfied the change is safe.
2. **The justification has to be rewritten to what is actually true**, which is still a perfectly good justification: implementing a published interface honestly beats a stub that answers OK for work not done, and the title links it. Just do not claim it is exercised.

---

## Blocking 2 — the export counts are wrong, and they hide something

> "prosper registers **5 of libSceFiber's 10** firmware exports" ... "*Uncharted* imports **four** of them" ... "The **three** remaining unregistered exports"

Against the firmware reference, libSceFiber has **15** exports. prosper registered **6** before this PR and **7** after. PPSA05684 imports **eight** of them, not four. The unregistered remainder is **eight**, not three:

| NID | name | imported by PPSA05684 |
|---|---|---|
| avfGJ94g36Q | _sceFiberAttachContextAndRun | no |
| ZqhZFuzKT6U | _sceFiberAttachContextAndSwitch | no |
| 0dy4JtMUcMQ | _sceFiberGetThreadFramePointerAddress | no |
| 7+OJIpko9RY | _sceFiberInitializeWithInternalOptionImpl | no |
| uq2Y5BFz0PE | sceFiberGetInfo | no |
| asjUJJ+aa8s | sceFiberOptParamInitialize | **yes** |
| Lcqty+QNWFc | sceFiberStartContextSizeCheck | no |
| Kj4nXMpnM8Y | sceFiberStopContextSizeCheck | no |

"5 of 10" is coherent only if "exports" silently means the ten non-underscore `sce*` ones — but even then prosper registers six, one of which (`hVYD7Ou2pCQ`) is underscore-prefixed. The sub-claim that GetInfo and the two ContextSizeCheck entries are not imported is **true**.

This is not just bookkeeping: the "three remaining" framing makes the four `_sce*` **alternate initialization paths** invisible, and those are precisely the set that determines whether returning an error from rename can regress a *different* title later. Please state the real surface.

---

## Blocking 3 — "cannot be implemented without the struct size" rests on the wrong tool

> "ran `tools/re/xref.py` — and that route does not reach the call site, because the NID is consumed by the *loader* rather than referenced by code"

The observation about the NID string is correct, and it is the exact problem two other tools in the same directory were written to solve. From `stub_nid_map.py`'s docstring: *"the NID never appears as a literal anywhere near the call."* From `nid_gate_scan.py`: *"NID -> dynsym index -> JMPREL jump-slot VA -> the `jmp *[rip+d]` stub that goes through it -> every `call rel32` that reaches the stub."*

Run it and the call site is there:

```
nid_gate_scan.py <DUMP_ROOT>/PPSA05684-app0/eboot.bin --nid 'asjUJJ+aa8s' -v
    call at 0x1f08 id=?       -> nonzero   test eax,eax
TOTAL nonzero=1
```

One call site, image-relative `0x1f08`, and the title branches on the result. Disassembling that caller and reading the stack allocation it hands the call is the direct, primary-evidence answer to the struct size — no PS4 SDK figure, no guess.

**Your decision not to implement it is right and I am not asking you to implement it here.** Do not guess a size; that part is charter-correct. But the stated *reason* — that the size is not obtainable — is not established, and left in the record it will stop the next agent from trying. Please soften it to "not yet derived" and name `nid_gate_scan.py` plus that address as the route, so the finding compounds instead of closing the door.

---

## Non-blocking

**No CONFIDENCE marker.** Three things here are genuinely reverse-engineered and none is derived from primary evidence, so the charter wants a `CONFIDENCE:` line:

* Whether a fiber in `kStateRun` should be refused. `fiber_finalize` refuses it; `fiber_rename` does not. I think permissive is the better default — inventing a refusal is the riskier error — but the asymmetry with its own sibling deserves one line saying it was a choice, not an oversight.
* Whether an over-long name truncates-and-returns-OK on hardware or is rejected with `SCE_FIBER_ERROR_RANGE`. prosper silently truncates and returns 0. If hardware rejects, that is the same "answered OK for work not fully done" divergence this PR's opening paragraph is written against.
* The `kErrInvalid` / `kErrNull` split itself.

`CONFIDENCE: MED` with those three named would be honest and costs two lines.

**The read-back story is not established.** The body says a guest "renames a fiber and then reads back the old name". The guest's route to a fiber's name is `sceFiberGetInfo` (`uq2Y5BFz0PE`) — unregistered, and **not imported by this title**. The only other route is the guest reading its own `SceFiber` directly, which requires prosper's `GuestFiber` layout to match Sony's, and nothing in the repo establishes that: the struct is prosper's own, with prosper-invented magic sentinels, introduced in #825 for Astro Bot. No new exposure is created (`fiber_initialize` already writes the same field at the same offset), but the body should not assert a read-back path prosper does not implement.

---

## To clear this

1. Fix the `hle_fiber.cpp:350` comment: linked, not exercised — zero statically reachable call sites in either boot binary, control passing.
2. Fix the counts in the body (15 exports, 6->7 registered, 8 imported, 8 unregistered).
3. Soften the optParam reasoning to "not yet derived", citing `nid_gate_scan.py` and `0x1f08`.
4. Relabel the mutation transcript as B2, or paste a real B1 run.
5. Optional: `CONFIDENCE: MED` and a line on the `kStateRun` choice.

No code change required for any of these. Re-request review and I will approve.

Reproduction for everything above: mutations applied to a detached worktree at this head, built and run in the ps5ys distrobox; scans are `python3 prosper/tools/re/nid_gate_scan.py` at this head against the local PPSA05684 dump.

**Review by mattias800 — COMMENTED** [review]
## APPROVED

Reviewed head **2a4740487eb0c563efe421fc4bbddb20632ed7e1** (PR-recorded head, remote branch tip, and my reviewed tree all agree; re-checked immediately before posting). This supersedes my REJECTED review on `8e01739ab`.

All five findings are fixed. I verified each against the tree and the binaries rather than against your summary, and one of my own checks went wrong on the way — see the count note below.

---

## The code did not change, and I confirmed that rather than assuming it

`fiber_rename`'s body is **byte-identical** between `8e01739ab` and this head, and `tests/hle/test_fiber.cpp` is **byte-identical**. The whole diff is the comment block (24 insertions, 13 deletions, one hunk). So my round-1 functional verification carries over unchanged: mutations A (1 arm), B1 (4 arms), B2 (2 arms), C (control fires on an offset move), D (truncation arm fires on a size change), and `ctest --no-tests=error` 509/509 exit 0.

I did **not** re-run the full 509 at this head, and I want that stated rather than implied — a comment-only diff against a head I already ran it on cannot change behaviour. What I did re-run, because a malformed comment is the one thing that could break: configure and build in the distrobox, `BUILD_RC=0`, and `test_fiber` → **9/9, `== PASS ==`**.

---

## Finding-by-finding

**1. "Exercised" — fixed, and fixed in the place that mattered most.** Gone from the body *and* from `hle_fiber.cpp`. The replacement comment states the measurement (zero call sites in both boot binaries, controlled against `hVYD7Ou2pCQ` / `a0LLrZWac0M` / `asjUJJ+aa8s`) and then says plainly that the justification is *not* "the guest exercises it". The narrower justification you land on — complete, no RE required, one bounded copy, removes a silent-wrong answer from a linked entry point, and explicitly does not extend to guessing a struct layout — is the one the evidence actually supports. This is now better than it would have been had the first version simply been right, because the comment carries the distinction that caused the error.

**2. Counts — correct. I re-derived them, and my first attempt was wrong.** Worth recording since I rejected you over counts:

My naive `grep -cE 'sprx_dlsym'` returned **16**, which would have made your corrected "15" wrong too. It is not — line 5 is the `int sprx_dlsym(unsigned int, const char*, void*);` **prototype**, not an export. Three independent counts agree on **15**: 15 binding lines, 15 unique NIDs, 15 `.global` directives. At this head prosper registers **7** unique NIDs (the `register_fn` grep returns 9 lines because the Windows and non-Windows branches each spell `sceFiberRun` and `sceFiberSwitch`). 15 − 7 = **8** remaining. Every number in the body checks out.

I reproduced the post-mortem too: `__ptr_sceFiber[A-Za-z]+` against the firmware file yields exactly **10**. The causal story is correct and reproducible.

*One imprecision, non-blocking:* the body says that pattern "excluded the four `_sceFiber*` alternates". It excludes **five** — the fifth being `_sceFiberInitializeImpl`, which prosper does register. Four are unregistered alternates, but five were excluded, and the arithmetic 15 − 5 = 10 only closes with five. Worth a one-word fix if you touch the body again; not worth a round trip on its own.

**3. optParam — fixed.** "Not done, rather than impossible" is the materially different claim, and it is the supportable one. `0x1f08` and `nid_gate_scan.py` are both named, so the next agent inherits the route instead of a closed door. I also checked the citation, since I made a point of citations last round: `hle_fiber.cpp:305-307` at **this** head is the `fiber_initialize` signature whose 7th parameter is an unnamed `const void*` — which is exactly the evidence that optParam is ignored. The line numbers survived the comment growth because the new text sits below them. Citation verified, not assumed.

**4. Mutation transcript — fixed.** The body now carries the four-arm output and says outright that the earlier two-arm evidence came from a different mutation than the one it was labelled as. It matches what I measured independently: true `return 0` → 4 arms, unregistered → 1 arm. The added sentence about the offset being guarded by the control and the size by the truncation arm is also correct — I verified both directions separately.

**5. CONFIDENCE — fixed, and correctly split.** HIGH on the copy and the NID mapping, LOW on exactly the three inferred semantics, each with its reasoning and the note that no corpus title can exercise them. The `kStateRun` entry states the reading it chose ("a name is metadata rather than context") rather than just asserting the behaviour, which is the useful form.

---

## On the thing you asked about

Keeping `"5 of 10"` inside the sentence that retracts it is **right, and I would not change it.** The charter's rule is not to correct a record, and a retraction that names what it retracts is how a reader tells a fix from a rewrite. If the string were removed, the correction would read as though the error had never happened.

---

## One non-blocking item, unrelated to my findings

The body still ends with a `🤖 Generated with [Claude Code]` attribution line. The charter forbids those in "PR bodies, commit messages, issue text, or comments — anywhere". Your **commit** is clean (trailer gate 0, no attribution line, single commit, `diff --check` clean), so this is only the body. It was there in round 1 and I did not raise it then, so it is not a regression from my review — just worth removing at some point. Not a reason to hold this.

---

## Gates I checked at this head

* PR head == remote branch tip == reviewed tree (re-checked at post time)
* Body verified as landed: 4536 bytes, fully rewritten, re-fetched immediately before posting
* `git log origin/main..HEAD --format=%B | grep -c '^Claude-Session:'` → **0**
* `git diff --check origin/main...HEAD` → clean
* Build `rc=0`; `test_fiber` 9/9 PASS

CI and the merge gate are yours to confirm at merge time — `pr_merge_gate.py` exits 2 rather than 0 when it cannot evaluate, so read the exit code rather than the absence of red.

Good correction. The round-2 comment is more useful to the next reader than a correct round-1 version would have been.

**Review by mattias800 — COMMENTED** [review]
## APPROVED

Re-affirming on head **dc251b830ba27fe0c8e486aeacbe2dc02c44cbd7**. My previous APPROVED sits on `2a4740487`, which is no longer head, so this exists so the verdict is attached to what would actually merge rather than leaving a merge gate to judge a detached review.

**The approval carries by content, established rather than assumed:**

```
tree   2a4740487 -> 9dbd84163540cc9dec389ee9f426cf6464ac300d
tree   dc251b830 -> 9dbd84163540cc9dec389ee9f426cf6464ac300d   (identical)
parent both       -> 267406bcda792ea0b2966a10d6c131a26a926f54  (identical)
git diff 2a4740487 dc251b830 -> 0 lines
```

Same tree *and* same parent, so this is an amend of the commit message, not a rebase. Not one byte of `hle_fiber.cpp` or `test_fiber.cpp` changed. Everything I verified at the previous head stands unchanged — including the build and `test_fiber` 9/9, which I am not re-running against an identical tree.

**Both non-blocking items I raised are addressed:**

* The commit message now says the pattern excluded the **five** leading-underscore entry points and names all of them, with `15 - 5 = 10` spelled out. The addition that the fifth (`_sceFiberInitializeImpl`) is one prosper already registers — so the pattern under-counted *both* the library and prosper's own coverage — is a better correction than the one I asked for; that second effect is the one that would have bitten a reader trying to reconcile the numbers.
* The `Generated with Claude Code` line is gone from the body.

**One residual, still non-blocking:** the fix landed in the commit message but not in the PR body, which still reads "excluded the four `_sceFiber*` alternates". The two now disagree. The squashed commit message is the durable record and it is the correct one, so this resolves itself at merge — but if you edit the body again, make it five there too. Every number that matters (15 exports, 6 to 7 registered, 8 remaining) is correct in both.

Nothing blocking. Good to merge once CI is green on this head — and note the head moved twice during review, so re-check `headRefOid` against the branch tip immediately before merging rather than relying on a check run that may describe an earlier SHA.
